### ISSUE TITLE
Issue with SteamVR Input system in the Standalone package 

### ISSUE THREAD

**Issue by jggrandi** [MartinFk/VRQuestionnaireToolkit#2]
First of all, thank you for this amazing toolkit. It will fit perfectly in my project. 
My issue is regarding the Standalone package that does not register controllers' input out of the box. (It may also extend to the Integration package as well).
The problem is that the Vive Input Utility action set is not generated after importing the toolkit.
Trying to reimport the Vive Input Utility prompts to the automatic action set generation, but a bug in Unity or SteamVR makes it impossible to create the actions.
I used the following steps to solve this issue:
- Create an empty project
- Import the SteamVR asset from the Asset Store (Accept all recommended settings in the windows that will pop up).
- Generate the SteamVR input (Window->SteamVR Input). Generate the example files and click and "Save and Generate". This step is solves the Vive Input Utility bug mentioned above.
- Import the Standalone package. 
- Import the Vive Input Utility from the Asset Store (Accept all recommended settings in the windows that will pop up). It will automatically generate the Vive Input Utility action set.

After these steps, I was able to use the controllers to input my actions into the forms.

I hope this is useful information to update the standalone package. 

--
Tested in Unity version 2019.4

**Comment by MartinFk** [comment]
Thank you very much for reaching out! We have tried to reproduce the error on 3 different Win10 machines (Unity version 2019.4), but we failed to do so:

- Created empty unity3d project
- Imported standalone version 
-> it worked (HTC Vive setup)

So, we do not know what is causing the issue, since we are unfortunately unable to replicate it. I am assuming it is caused on the SteamVR side. 

I am glad that you eventually found a way getting it to work. 

If someone else stumbles across the same issue, please let us know!

**Comment by MartinFk** [comment]
Thank you very much for reaching out! We have tried reproducing the error on 3 different Win10 machines (Unity version 2019.4), but we failed to do so:

- Created empty unity3d project
- Imported standalone version
-> it worked (HTC Vive setup)

So, we do not know what is causing the issue, since we are unfortunately unable to replicate it. I am assuming it is caused on the SteamVR side. I'll spent some time on the weekend looking into this.

I am glad that you eventually found a way getting it to work.

If someone else stumbles across the same issue, please let us know!
